[tool.poetry]
name = "pricera.rozetka"
version = "0.1.0"
description = ""
authors = []
packages=[
    {include="pricera/rozetka/*"}
]

[tool.poetry.dependencies]
python = ">=3.13"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.core.masonry.api"
